version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: java
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  spring-boot-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"




